kind: pipeline
type: docker
name: default

steps:
- name: Building
  image: ubuntu:18.04
  environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
  commands:
  - apt update
  - apt install -y curl git 
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.68.3/hugo_extended_0.68.3_Linux-64bit.deb
  - dpkg -i hugo_extended_0.68.3_Linux-64bit.deb
  - git clone --single-branch --branch source http://git.kenmlai.me:3000/ken/kenmlai.me.git source
  - cd source
  - git clone --single-branch --branch content http://git.kenmlai.me:3000/ken/kenmlai.me.git content
  - hugo
  - cd public
  - echo "kenlai.me" > CNAME
  - git init
  - git config user.name "KenMercusLai"
  - git config user.email "ken.mercus.lai@gmail.com"
  - git add .
  - git commit -m "$(date)"
  - git remote add origin https://$GITHUB_TOKEN@github.com/KenMercusLai/kenmercuslai.github.io.git
  - git remote -v
  - git push origin master -f
- name: send telegram notification
  image: appleboy/drone-telegram
  settings:
    token: 916936183:AAEd7rp8lfehiRap39nMaP27WG2eDruCZy4
    to: 927863874
  when:
    status:
    - success
    - failure
