kind: pipeline
type: docker
name: default

steps:
- name: Building
  image: ubuntu:18.04
  commands:
  - apt update
  - apt install -y hugo git
  - git clone --single-branch --branch source https://github.com/KenMercusLai/kenmercuslai.github.io.git source
  - cd source
  - git clone --single-branch --branch content https://github.com/KenMercusLai/kenmercuslai.github.io.git content
  - hugo -D
  - cd public
  - echo "kenmlai.me" > CNAME
  - git init
  - git config user.name "KenMercusLai"
  - git config user.email "ken.mercus.lai@gmail.com"
  - git add .
  - git commit -m "$(date)"
  - git remote add origin https://${GITHUB_TOKEN}@github.com/KenMercusLai/kenmercuslai.github.io.git
  - git remote -v
  - git push origin master -f