language: go
branches:
  only:
    - source
    - content
github_token: $GITHUB_TOKEN
before_install:
  - git clone --single-branch --branch source https://github.com/KenMercusLai/kenmercuslai.github.io.git source
  - cd source
  - git clone --single-branch --branch content https://github.com/KenMercusLai/kenmercuslai.github.io.git _posts
script:
  - bundle exec jekyll build
# after_success:
#   - cd _site
#   - echo "kenmlai.me" > CNAME
#   - git init
#   - git config user.name "KenMercusLai"
#   - git config user.email "ken.mercus.lai@gmail.com"
#   - git add .
#   - git commit -m "$(date)"
#   - git remote add origin https://${GITHUB_TOKEN}@github.com/KenMercusLai/kenmercuslai.github.io.git
#   - git remote -v
#   - git push origin master -f
notifications:
  email:
    recipients:
      - ken.mercus.lai@gmail.com
    on_success: never
    on_failure: always
