# hugo server --minify --themesDir ... --baseURL=http://0.0.0.0:1313/theme/hugo-book/

baseURL: https://kenlai.me/
theme: jane
title: Engineering Field Notes
enableRobotsTXT: true
enableEmoji: true
hasCJKLanguage: true

# Book configuration
# (Optional) Set Google Analytics if you use it to track your website.
# Always put it on the top of the configuration file, otherwise it won't work
googleAnalytics: "UA-26670277-1"

# (Optional) If you provide a Disqus shortname, comments will be enabled on
# all pages.
# disqusShortname: "kenmlaime"
disqusShortname: ""
disablePathToLower: true
enableGitInfo: false

# Highlight options.
# See https://gohugo.io/content-management/syntax-highlighting/
PygmentsCodeFences: true # Enable syntax highlighting with GitHub flavoured code fences
PygmentsUseClasses: true # Use CSS classes to format highlighted code
PygmentsCodefencesGuessSyntax: true
PygmentsOptions: "linenos=table"

author:                  # essential                     # 必需
  name: Ken Lai

sitemap:                 # essential                     # 必需
  changefreq: "weekly"
  priority: 0.5
  filename: "sitemap.xml"

menu: 
  main:             # config your menu              # 配置目录
  - name: "Home"
    weight: 10
    identifier: "home"
    url: "/"
  - name: "Archives"
    weight: 20
    identifier: "archives"
    url: "/post/"
  - name: "Tags"
    weight: 30
    identifier: "tags"
    url: "/tags/"
  # - name: "Links"
  #   weight: 40
  #   identifier: "links"
  #   url: "/links/"

params:
  since: "2013"            # Site creation time          # 站点建立时间
  homeFullContent: false   # if false, show post summaries on home page. Otherwise show full content.
  rssFullContent: false   # if false, Rss feed instead of the summary

  # site info (optional)                                  # 站点信息（可选，不需要的可以直接注释掉）
  logoTitle: "Engineering Field Notes"        # default: the title value    # 默认值: 上面设置的title值
  keywords: ["Network", "Automation","Notes", "Thoughts"]
  description: "Notes and thoughts about network"

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse: "2006-01-02"

  # 一些全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能，在 archetypes/default.md 查看更多信息。
  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc: true                                                                            # 是否开启目录
  photoswipe: true         # see https://github.com/dimsemenov/PhotoSwipe            # 是否启用PhotoSwipe（图片可点击）
  contentCopyright: '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'
  mathjax: false           # see https://www.mathjax.org/                              # 是否使用mathjax（数学公式）
  katex: false             # see https://github.com/KaTeX/KaTeX

  showAuthorInfo: true # show author info below the article

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  # customCSS: []            # if ['custom.css'], load '/static/css/custom.css' file
  # customJS: []             # if ['custom.js'], load '/static/js/custom.js' file

  # show word count and read time ?                       # 是否显示字数统计与阅读时间
  moreMeta: true

  social:                                         # 社交链接
    a-email: "mailto:ken.mercus.lai@gmail.com"
    c-twitter: "https://twitter.com/Ken_M_Lai"
    e-linkedin: "https://www.linkedin.com/in/kenmercuslai/"

  # Valine.
  # You can get your appid and appkey from https://leancloud.cn
  # more info please open https://valine.js.org
  valine:
    enable: enable
    appId: 'HRVXwifaSeWcsjMaWIeaMCxa-MdYXbMMI'
    appKey: 'NxTb7qTWsfkjJ6Xoutu8x9bh'
    notify: false  # If you are using valine-admin(https://github.com/DesertsP/Valine-Admin) to notify users, do NOT enable this.
    verify: false # Verification code
    avatar: 'mm'
    placeholder: ''

  # [params.search.google]    # google custom search, see https://cse.google.com
  #   enable = false
    # id = "002186711602136249422:q1gkomof_em"
    # title = "Search"

  #   [params.reward]                                         # 文章打赏
  #   enable = false
  #   wechat = "/path/to/your/wechat-qr-code.png"           # 微信二维码
  #   alipay = "/path/to/your/alipay-qr-code.png"           # 支付宝二维码

  counter:
    busuanzi:  # a Chinese visitor counter  # 不蒜子计数器
      enable: true

  # leancloud:  # Chinese leancloud visitor counter  # leancloud 计数器
  #   enable = false
  #   appId = ""
  #   appKey = ""

  # [params.commentCount.disqus] # show counts of comments for Disqus
  #   enable = false