# hugo server --minify --themesDir ... --baseURL=http://0.0.0.0:1313/theme/hugo-book/

baseURL: https://kenlai.me/
theme: jane
title: Engineering Field Notes
enableRobotsTXT: true
enableEmoji: true
hasCJKLanguage: true

# Book configuration
# (Optional) Set Google Analytics if you use it to track your website.
# Always put it on the top of the configuration file, otherwise it won't work
googleAnalytics: "UA-26670277-1"

# (Optional) If you provide a Disqus shortname, comments will be enabled on
# all pages.
disqusShortname: "kenmlaime"
disablePathToLower: true
enableGitInfo: true

# Needed for mermaid/katex shortcodes
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1

author:                  # essential                     # 必需
  name: Ken Lai

sitemap:                 # essential                     # 必需
  changefreq: "weekly"
  priority: 0.5
  filename: "sitemap.xml"

menu:
  # before: []
  after:
    - name: "Linkedin"
      url: "https://www.linkedin.com/in/kenmercuslai/"
      weight: 10
    - name: "Twitter"
      url: "https://twitter.com/Ken_M_Lai"
      weight: 15

params:
  since: "2014"            # Site creation time          # 站点建立时间
  homeFullContent: false   # if false, show post summaries on home page. Otherwise show full content.
  rssFullContent: false   # if false, Rss feed instead of the summary

