#+OPTIONS: toc:nil

I've been collecting documents and articles related to my work and life. The oldest file dates back for more than 10 years. I'm actively learning and trying studying methods to get more from what I've collected to avoid [[https://zettelkasten.de/posts/collectors-fallacy/][The Collector's Fallacy]]. 

I'd like to consider myself lucky to finally land on DEVONthink for storing all my files with its power searching capability. I dump all sources of information into it for later processing and organizing. Its biggest drawback is its advantage - managing documents. Anything beyond this reveals its awkwardness, especially in writing notes and building knowledge networks, which are emphasized by Zettelkasten and Roam Study a lot. 

There're a lot of tools and apps for the knowledge work outside of the DEVONthink: The Archive, RoamSearch, and some plugins for VSC and Sublime Text. They matched most of my core requests for:
1. using plain text. Proprietory formats cause lock-in and may potentially lose data because of incompatibility.
2. Use out-of-box with customization available. Bending my habits in one software may not worthy in my perspective.
3. Mature and longevity. I don't need to worry about breaking changes and lose all data if the app/service discontinues.

Besides these three criteria, I prefer to be able to dump my thoughts, like tasks, ideas, and quick notes, to the tool and let it process mostly, so I only need to work on things that require my attention and intelligent work. This is because I'm tired of constantly switching to OmniFocus to check my tasks and its close eco-system. After googling a while, Emacs-based or-gmode impressed me, and I decided to go with it. 

Emacs is probably one of the best well-known and iconic open-source software. Someone refers Emacs as the Gods' editor which is so flexible that it works like an OS instead of just an editor. I have never doubted its powerfulness but never had a positive experience until recently. The major reason was its steep learning curve of non-intuitive combinations of shortcuts. It's a hell of shortcuts and isn't friendly to all modern users.

So I decided to open a series to log down my experience to help newcomers to pick this great tool quicker. My goal is to use org-mode to assistant me as much as possible, and I will tune my setting to serve this purpose and programming in Emacs has never been my aim.
